ARG BUILD_WORKDIR=/go/src/github.com/yamt/midonet-kubernetes

FROM golang:1.10.1 as builder
ARG BUILD_WORKDIR
LABEL maintainer "YAMAMOTO Takashi <yamamoto@midokura.com>"
WORKDIR ${BUILD_WORKDIR}
COPY . .
RUN CGO_ENABLED=0 go build -v -o midonet-kube-node ./cmd/midonet-kube-node
RUN CGO_ENABLED=0 go build -v -o midonet-kube-cni ./cmd/midonet-kube-cni

FROM alpine:3.7
LABEL maintainer "YAMAMOTO Takashi <yamamoto@midokura.com>"
ARG BUILD_WORKDIR
WORKDIR /root/
COPY node-scripts .
COPY --from=builder ${BUILD_WORKDIR}/midonet-kube-node .
COPY --from=builder ${BUILD_WORKDIR}/midonet-kube-cni .
CMD ["./main"]
