/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	midonet_v1 "github.com/midonet/midonet-kubernetes/pkg/apis/midonet/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTranslations implements TranslationInterface
type FakeTranslations struct {
	Fake *FakeMidonetV1
	ns   string
}

var translationsResource = schema.GroupVersionResource{Group: "midonet.org", Version: "v1", Resource: "translations"}

var translationsKind = schema.GroupVersionKind{Group: "midonet.org", Version: "v1", Kind: "Translation"}

// Get takes name of the translation, and returns the corresponding translation object, and an error if there is any.
func (c *FakeTranslations) Get(name string, options v1.GetOptions) (result *midonet_v1.Translation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(translationsResource, c.ns, name), &midonet_v1.Translation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*midonet_v1.Translation), err
}

// List takes label and field selectors, and returns the list of Translations that match those selectors.
func (c *FakeTranslations) List(opts v1.ListOptions) (result *midonet_v1.TranslationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(translationsResource, translationsKind, c.ns, opts), &midonet_v1.TranslationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &midonet_v1.TranslationList{}
	for _, item := range obj.(*midonet_v1.TranslationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested translations.
func (c *FakeTranslations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(translationsResource, c.ns, opts))

}

// Create takes the representation of a translation and creates it.  Returns the server's representation of the translation, and an error, if there is any.
func (c *FakeTranslations) Create(translation *midonet_v1.Translation) (result *midonet_v1.Translation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(translationsResource, c.ns, translation), &midonet_v1.Translation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*midonet_v1.Translation), err
}

// Update takes the representation of a translation and updates it. Returns the server's representation of the translation, and an error, if there is any.
func (c *FakeTranslations) Update(translation *midonet_v1.Translation) (result *midonet_v1.Translation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(translationsResource, c.ns, translation), &midonet_v1.Translation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*midonet_v1.Translation), err
}

// Delete takes name of the translation and deletes it. Returns an error if one occurs.
func (c *FakeTranslations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(translationsResource, c.ns, name), &midonet_v1.Translation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTranslations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(translationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &midonet_v1.TranslationList{})
	return err
}

// Patch applies the patch and returns the patched translation.
func (c *FakeTranslations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *midonet_v1.Translation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(translationsResource, c.ns, name, data, subresources...), &midonet_v1.Translation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*midonet_v1.Translation), err
}
