/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/yamt/midonet-kubernetes/pkg/apis/midonet/v1"
	scheme "github.com/yamt/midonet-kubernetes/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TranslationsGetter has a method to return a TranslationInterface.
// A group's client should implement this interface.
type TranslationsGetter interface {
	Translations(namespace string) TranslationInterface
}

// TranslationInterface has methods to work with Translation resources.
type TranslationInterface interface {
	Create(*v1.Translation) (*v1.Translation, error)
	Update(*v1.Translation) (*v1.Translation, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.Translation, error)
	List(opts meta_v1.ListOptions) (*v1.TranslationList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Translation, err error)
	TranslationExpansion
}

// translations implements TranslationInterface
type translations struct {
	client rest.Interface
	ns     string
}

// newTranslations returns a Translations
func newTranslations(c *MidonetV1Client, namespace string) *translations {
	return &translations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the translation, and returns the corresponding translation object, and an error if there is any.
func (c *translations) Get(name string, options meta_v1.GetOptions) (result *v1.Translation, err error) {
	result = &v1.Translation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("translations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Translations that match those selectors.
func (c *translations) List(opts meta_v1.ListOptions) (result *v1.TranslationList, err error) {
	result = &v1.TranslationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("translations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested translations.
func (c *translations) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("translations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a translation and creates it.  Returns the server's representation of the translation, and an error, if there is any.
func (c *translations) Create(translation *v1.Translation) (result *v1.Translation, err error) {
	result = &v1.Translation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("translations").
		Body(translation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a translation and updates it. Returns the server's representation of the translation, and an error, if there is any.
func (c *translations) Update(translation *v1.Translation) (result *v1.Translation, err error) {
	result = &v1.Translation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("translations").
		Name(translation.Name).
		Body(translation).
		Do().
		Into(result)
	return
}

// Delete takes name of the translation and deletes it. Returns an error if one occurs.
func (c *translations) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("translations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *translations) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("translations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched translation.
func (c *translations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Translation, err error) {
	result = &v1.Translation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("translations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
