// Code generated by protoc-gen-go. DO NOT EDIT.
// source: noderpc.proto

package nodeapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddPodAnnotationRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPodAnnotationRequest) Reset()         { *m = AddPodAnnotationRequest{} }
func (m *AddPodAnnotationRequest) String() string { return proto.CompactTextString(m) }
func (*AddPodAnnotationRequest) ProtoMessage()    {}
func (*AddPodAnnotationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_e896e40e4d31448e, []int{0}
}
func (m *AddPodAnnotationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPodAnnotationRequest.Unmarshal(m, b)
}
func (m *AddPodAnnotationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPodAnnotationRequest.Marshal(b, m, deterministic)
}
func (dst *AddPodAnnotationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPodAnnotationRequest.Merge(dst, src)
}
func (m *AddPodAnnotationRequest) XXX_Size() int {
	return xxx_messageInfo_AddPodAnnotationRequest.Size(m)
}
func (m *AddPodAnnotationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPodAnnotationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPodAnnotationRequest proto.InternalMessageInfo

func (m *AddPodAnnotationRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AddPodAnnotationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddPodAnnotationRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddPodAnnotationRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AddPodAnnotationReply struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPodAnnotationReply) Reset()         { *m = AddPodAnnotationReply{} }
func (m *AddPodAnnotationReply) String() string { return proto.CompactTextString(m) }
func (*AddPodAnnotationReply) ProtoMessage()    {}
func (*AddPodAnnotationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_e896e40e4d31448e, []int{1}
}
func (m *AddPodAnnotationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPodAnnotationReply.Unmarshal(m, b)
}
func (m *AddPodAnnotationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPodAnnotationReply.Marshal(b, m, deterministic)
}
func (dst *AddPodAnnotationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPodAnnotationReply.Merge(dst, src)
}
func (m *AddPodAnnotationReply) XXX_Size() int {
	return xxx_messageInfo_AddPodAnnotationReply.Size(m)
}
func (m *AddPodAnnotationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPodAnnotationReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddPodAnnotationReply proto.InternalMessageInfo

func (m *AddPodAnnotationReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*AddPodAnnotationRequest)(nil), "nodeapi.AddPodAnnotationRequest")
	proto.RegisterType((*AddPodAnnotationReply)(nil), "nodeapi.AddPodAnnotationReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MidoNetKubeNodeClient is the client API for MidoNetKubeNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MidoNetKubeNodeClient interface {
	AddPodAnnotation(ctx context.Context, in *AddPodAnnotationRequest, opts ...grpc.CallOption) (*AddPodAnnotationReply, error)
}

type midoNetKubeNodeClient struct {
	cc *grpc.ClientConn
}

func NewMidoNetKubeNodeClient(cc *grpc.ClientConn) MidoNetKubeNodeClient {
	return &midoNetKubeNodeClient{cc}
}

func (c *midoNetKubeNodeClient) AddPodAnnotation(ctx context.Context, in *AddPodAnnotationRequest, opts ...grpc.CallOption) (*AddPodAnnotationReply, error) {
	out := new(AddPodAnnotationReply)
	err := c.cc.Invoke(ctx, "/nodeapi.MidoNetKubeNode/AddPodAnnotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MidoNetKubeNodeServer is the server API for MidoNetKubeNode service.
type MidoNetKubeNodeServer interface {
	AddPodAnnotation(context.Context, *AddPodAnnotationRequest) (*AddPodAnnotationReply, error)
}

func RegisterMidoNetKubeNodeServer(s *grpc.Server, srv MidoNetKubeNodeServer) {
	s.RegisterService(&_MidoNetKubeNode_serviceDesc, srv)
}

func _MidoNetKubeNode_AddPodAnnotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPodAnnotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidoNetKubeNodeServer).AddPodAnnotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeapi.MidoNetKubeNode/AddPodAnnotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidoNetKubeNodeServer).AddPodAnnotation(ctx, req.(*AddPodAnnotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MidoNetKubeNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodeapi.MidoNetKubeNode",
	HandlerType: (*MidoNetKubeNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPodAnnotation",
			Handler:    _MidoNetKubeNode_AddPodAnnotation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noderpc.proto",
}

func init() { proto.RegisterFile("noderpc.proto", fileDescriptor_noderpc_e896e40e4d31448e) }

var fileDescriptor_noderpc_e896e40e4d31448e = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcb, 0x4f, 0x49,
	0x2d, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x71, 0x13, 0x0b, 0x32,
	0x95, 0x8a, 0xb9, 0xc4, 0x1d, 0x53, 0x52, 0x02, 0xf2, 0x53, 0x1c, 0xf3, 0xf2, 0xf2, 0x4b, 0x12,
	0x4b, 0x32, 0xf3, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0xf3,
	0x12, 0x73, 0x53, 0x8b, 0x0b, 0x12, 0x93, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10,
	0x02, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0x8e, 0x04, 0x13, 0x58, 0x02, 0xcc, 0x16, 0x12, 0xe0, 0x62,
	0xce, 0x4e, 0xad, 0x94, 0x60, 0x06, 0x0b, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39,
	0xa5, 0xa9, 0x12, 0x2c, 0x60, 0x31, 0x08, 0x47, 0x49, 0x97, 0x4b, 0x14, 0xd3, 0xd2, 0x82, 0x1c,
	0xb0, 0xf2, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0xa8, 0x75, 0x10, 0x8e, 0x51, 0x26, 0x17, 0xbf, 0x6f,
	0x66, 0x4a, 0xbe, 0x5f, 0x6a, 0x89, 0x77, 0x69, 0x52, 0xaa, 0x5f, 0x7e, 0x4a, 0xaa, 0x50, 0x18,
	0x97, 0x00, 0xba, 0x09, 0x42, 0x0a, 0x7a, 0x50, 0x4f, 0xe9, 0xe1, 0xf0, 0x91, 0x94, 0x1c, 0x1e,
	0x15, 0x05, 0x39, 0x95, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0xe0, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x68, 0x21, 0x67, 0x2f, 0x01, 0x00, 0x00,
}
